package helpers;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;

public class ScreenShots {
    public static void takeScreenShot(String screenName, WebDriver driver) {
        File mySSFAIL = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        try {
            FileUtils.copyFile(mySSFAIL, new File("screenName" + "_" + System.currentTimeMillis() + ".png"));
        } catch (IOException e) {
            // TODO autogenerated
            e.printStackTrace();
        }

    }
}
